module.exports.ingredientArray = [
  "tomato",
  "pineapple",
  "orange",
  "olive oil",
  "black beans",
  "onion",
  "garlic",
  "kidney beans",
  "olives",
  "noodles",
  "sausage",
  "duck sausage",
  "hot italian sausage",
  "mild italian sausage",
  "white bread",
  "whole wheat bread",
  "egg",
  "flour",
  "cauliflower",
  "brocolli",
  "green beans",
  "shaved beef steak",
  "steak",
  "lentils",
  "bone broth",
  "chicken stock",
  "turkey stock",
  "vegetable stock",
  "cheese",
  "mozzarella cheese",
];
